//! Icon mapping. Uses Phosphor icons (MIT), not Adobe's icon assets.

pub use egui_phosphor::regular::*;

use op_tools::Tool;

pub fn tool(tool: Tool) -> &'static str {
    use Tool::*;
    match tool {
        Move => ARROWS_OUT_CARDINAL,
        Artboard => LAYOUT,
        RectangularMarquee => SELECTION,
        EllipticalMarquee => CIRCLE_DASHED,
        SingleRowMarquee => ARROWS_HORIZONTAL,
        SingleColumnMarquee => ARROWS_VERTICAL,
        Lasso => LASSO,
        PolygonalLasso => POLYGON,
        MagneticLasso => MAGNET,
        ObjectSelection => SELECTION_PLUS,
        QuickSelection => PAINT_BRUSH_HOUSEHOLD,
        MagicWand => MAGIC_WAND,
        Crop => CROP,
        PerspectiveCrop => PERSPECTIVE,
        Slice => KNIFE,
        SliceSelect => CURSOR,
        Frame => FRAME_CORNERS,
        Eyedropper => EYEDROPPER,
        ColorSampler => EYEDROPPER_SAMPLE,
        Ruler => RULER,
        Note => NOTE,
        Count => HASH,
        SpotHealingBrush => BANDAIDS,
        Remove => SPARKLE,
        HealingBrush => FIRST_AID,
        Patch => SQUARE_HALF_BOTTOM,
        ContentAwareMove => ARROWS_OUT,
        RedEye => EYE,
        Brush => PAINT_BRUSH,
        Pencil => PENCIL,
        ColorReplacement => PAINT_BRUSH_HOUSEHOLD,
        MixerBrush => PAINT_BRUSH_HOUSEHOLD,
        CloneStamp => STAMP,
        PatternStamp => STAMP,
        HistoryBrush => PAINT_BRUSH_BROAD,
        ArtHistoryBrush => SCRIBBLE_LOOP,
        Eraser => ERASER,
        BackgroundEraser => ERASER,
        MagicEraser => ERASER,
        Gradient => GRADIENT,
        PaintBucket => PAINT_BUCKET,
        Blur => DROP,
        Sharpen => TRIANGLE,
        Smudge => HAND_POINTING,
        Dodge => DROP_HALF,
        Burn => HAND_FIST,
        Sponge => DROP_HALF_BOTTOM,
        Pen => PEN_NIB,
        FreeformPen => PEN,
        CurvaturePen => BEZIER_CURVE,
        AddAnchorPoint => PLUS,
        DeleteAnchorPoint => MINUS,
        ConvertPoint => CARET_UP,
        HorizontalType => TEXT_T,
        VerticalType => TEXT_AA,
        VerticalTypeMask => TEXT_T_SLASH,
        HorizontalTypeMask => TEXT_T_SLASH,
        PathSelection => NAVIGATION_ARROW,
        DirectSelection => CURSOR,
        Rectangle => RECTANGLE,
        Ellipse => CIRCLE,
        Triangle => TRIANGLE,
        Polygon => POLYGON,
        Line => LINE_SEGMENT,
        CustomShape => STAR,
        Hand => HAND,
        RotateView => ARROW_CLOCKWISE,
        Zoom => MAGNIFYING_GLASS,
    }
}
